In [1]:
!pip3 install --upgrade pip

In [2]:
import pandas as pd

/var/folders/qx/vfr8b98x3m96_l4x2q960pwm0000gn/T/ipykernel_10527/4080736814.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [3]:
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
Invest  = pd.read_csv('final_transactions_dataset.csv')

In [5]:
Invest1 = Invest[0:200000]


In [6]:
Invest1.describe

<bound method NDFrame.describe of         Unnamed: 0 company  sector  horizon (days)  amount date_BUY_fix  \
0                0     BBY  RETAIL               2     100   2017-05-25   
1                1     BAC    BANK             330   15000   2016-11-22   
2                2     AXP    BANK               7    3000   2016-09-27   
3                3     KSS  RETAIL               5   20000   2016-10-11   
4                4     JPM    BANK             360   15000   2015-03-12   
...            ...     ...     ...             ...     ...          ...   
199995      246667      GM    AUTO             120     500   2015-06-09   
199996      246668      GM    AUTO             150    1500   2014-03-04   
199997      246669     JPM    BANK             270    1500   2016-09-19   
199998      246670     HMC    AUTO              90    2000   2015-01-16   
199999      246671      DB    BANK              80    4000   2016-12-27   

       date_SELL_fix  price_BUY  price_SELL  Volatility_Buy  ... 

In [7]:
Return = Invest1['nominal_return']

In [8]:
Invest2 = Invest1.drop(['Volatility_Buy','expected_return (yearly)','Unnamed: 0','company','sector','date_BUY_fix','date_SELL_fix','price_SELL','Volatility_sell','investment','Sharpe Ratio','PE_ratio','PS_ratio','PB_ratio'], axis = 1)

In [9]:
Invest2

horizon (days)  amount  price_BUY  inflation  nominal_return  \
0                    2     100  55.551804       1.96       -0.037225   
1                  330   15000  18.616749      -0.20        0.324317   
2                    7    3000  59.862297      -0.20       -0.005756   
3                    5   20000  38.216724      -0.20       -0.058388   
4                  360   15000  51.869335      -0.50        0.003444   
...                ...     ...        ...        ...             ...   
199995             120     500  28.741871      -0.50       -0.051145   
199996             150    1500  28.542963      -0.15       -0.078845   
199997             270    1500  58.351299      -0.20        0.326308   
199998              90    2000  30.840000      -0.50        0.136835   
199999              80    4000  17.665504      -0.20        0.035928   

        ESG_ranking  EPS_ratio  NetProfitMargin_ratio  current_ratio  \
0              12.0       3.73                   3.01           1.49   
1              26.3       1.26                  15.70           0.92   
2              19.8       5.64                  15.68           1.91   
3              12.9       3.27                   3.17           1.60   
4              27.9       5.46                  19.91           0.99   
...             ...        ...                    ...            ...   
199995         30.6       2.70                   2.98           1.22   
199996         30.6       1.83                   1.94           1.25   
199997         27.9       5.80                  20.86           1.04   
199998         28.5       3.08                   4.83           1.23   
199999         30.0      -1.31                  -3.43           0.75   

        roa_ratio  roe_ratio  
0            8.69      26.69  
1            0.67       5.54  
2            3.39      25.78  
3            4.41      11.35  
4            0.81       8.91  
...           ...        ...  
199995       2.53      11.97  
199996       1.80       7.46  
199997       0.89       8.66  
199998       3.65       9.24  
199999      -0.08      -2.10  

[200000 rows x 11 columns]

In [10]:
Invest2.shape

(200000, 11)

In [11]:
Return_A = Invest2.iloc[:,6].values


In [12]:
Return_A.shape

(200000,)

In [13]:
Return.shape

(200000,)

In [14]:
Invest3 =Invest2.drop(['nominal_return'], axis = 1)


In [15]:
Invest2.shape

(200000, 11)

In [16]:
Invest3.shape

(200000, 10)

In [17]:
Invest3

horizon (days)  amount  price_BUY  inflation  ESG_ranking  EPS_ratio  \
0                    2     100  55.551804       1.96         12.0       3.73   
1                  330   15000  18.616749      -0.20         26.3       1.26   
2                    7    3000  59.862297      -0.20         19.8       5.64   
3                    5   20000  38.216724      -0.20         12.9       3.27   
4                  360   15000  51.869335      -0.50         27.9       5.46   
...                ...     ...        ...        ...          ...        ...   
199995             120     500  28.741871      -0.50         30.6       2.70   
199996             150    1500  28.542963      -0.15         30.6       1.83   
199997             270    1500  58.351299      -0.20         27.9       5.80   
199998              90    2000  30.840000      -0.50         28.5       3.08   
199999              80    4000  17.665504      -0.20         30.0      -1.31   

        NetProfitMargin_ratio  current_ratio  roa_ratio  roe_ratio  
0                        3.01           1.49       8.69      26.69  
1                       15.70           0.92       0.67       5.54  
2                       15.68           1.91       3.39      25.78  
3                        3.17           1.60       4.41      11.35  
4                       19.91           0.99       0.81       8.91  
...                       ...            ...        ...        ...  
199995                   2.98           1.22       2.53      11.97  
199996                   1.94           1.25       1.80       7.46  
199997                  20.86           1.04       0.89       8.66  
199998                   4.83           1.23       3.65       9.24  
199999                  -3.43           0.75      -0.08      -2.10  

[200000 rows x 10 columns]

In [18]:
Invest3.shape

(200000, 10)

In [19]:
Invest3

horizon (days)  amount  price_BUY  inflation  ESG_ranking  EPS_ratio  \
0                    2     100  55.551804       1.96         12.0       3.73   
1                  330   15000  18.616749      -0.20         26.3       1.26   
2                    7    3000  59.862297      -0.20         19.8       5.64   
3                    5   20000  38.216724      -0.20         12.9       3.27   
4                  360   15000  51.869335      -0.50         27.9       5.46   
...                ...     ...        ...        ...          ...        ...   
199995             120     500  28.741871      -0.50         30.6       2.70   
199996             150    1500  28.542963      -0.15         30.6       1.83   
199997             270    1500  58.351299      -0.20         27.9       5.80   
199998              90    2000  30.840000      -0.50         28.5       3.08   
199999              80    4000  17.665504      -0.20         30.0      -1.31   

        NetProfitMargin_ratio  current_ratio  roa_ratio  roe_ratio  
0                        3.01           1.49       8.69      26.69  
1                       15.70           0.92       0.67       5.54  
2                       15.68           1.91       3.39      25.78  
3                        3.17           1.60       4.41      11.35  
4                       19.91           0.99       0.81       8.91  
...                       ...            ...        ...        ...  
199995                   2.98           1.22       2.53      11.97  
199996                   1.94           1.25       1.80       7.46  
199997                  20.86           1.04       0.89       8.66  
199998                   4.83           1.23       3.65       9.24  
199999                  -3.43           0.75      -0.08      -2.10  

[200000 rows x 10 columns]

In [20]:
Invest3

horizon (days)  amount  price_BUY  inflation  ESG_ranking  EPS_ratio  \
0                    2     100  55.551804       1.96         12.0       3.73   
1                  330   15000  18.616749      -0.20         26.3       1.26   
2                    7    3000  59.862297      -0.20         19.8       5.64   
3                    5   20000  38.216724      -0.20         12.9       3.27   
4                  360   15000  51.869335      -0.50         27.9       5.46   
...                ...     ...        ...        ...          ...        ...   
199995             120     500  28.741871      -0.50         30.6       2.70   
199996             150    1500  28.542963      -0.15         30.6       1.83   
199997             270    1500  58.351299      -0.20         27.9       5.80   
199998              90    2000  30.840000      -0.50         28.5       3.08   
199999              80    4000  17.665504      -0.20         30.0      -1.31   

        NetProfitMargin_ratio  current_ratio  roa_ratio  roe_ratio  
0                        3.01           1.49       8.69      26.69  
1                       15.70           0.92       0.67       5.54  
2                       15.68           1.91       3.39      25.78  
3                        3.17           1.60       4.41      11.35  
4                       19.91           0.99       0.81       8.91  
...                       ...            ...        ...        ...  
199995                   2.98           1.22       2.53      11.97  
199996                   1.94           1.25       1.80       7.46  
199997                  20.86           1.04       0.89       8.66  
199998                   4.83           1.23       3.65       9.24  
199999                  -3.43           0.75      -0.08      -2.10  

[200000 rows x 10 columns]

In [21]:

Invest_A = Invest3.iloc[:,0:12].values


In [22]:
Invest_A[0:4]

array([[ 2.00000000e+00,  1.00000000e+02,  5.55518036e+01,
         1.96000000e+00,  1.20000000e+01,  3.73000000e+00,
         3.01000000e+00,  1.49000000e+00,  8.69000000e+00,
         2.66900000e+01],
       [ 3.30000000e+02,  1.50000000e+04,  1.86167488e+01,
        -2.00000000e-01,  2.63000000e+01,  1.26000000e+00,
         1.57000000e+01,  9.20000000e-01,  6.70000000e-01,
         5.54000000e+00],
       [ 7.00000000e+00,  3.00000000e+03,  5.98622971e+01,
        -2.00000000e-01,  1.98000000e+01,  5.64000000e+00,
         1.56800000e+01,  1.91000000e+00,  3.39000000e+00,
         2.57800000e+01],
       [ 5.00000000e+00,  2.00000000e+04,  3.82167244e+01,
        -2.00000000e-01,  1.29000000e+01,  3.27000000e+00,
         3.17000000e+00,  1.60000000e+00,  4.41000000e+00,
         1.13500000e+01]])

In [23]:
Invest_A.shape

(200000, 10)

In [24]:
from sklearn.model_selection import train_test_split

Invest_train, Invest_test, Return_train, Return_test = train_test_split(Invest_A, Return_A, test_size = 0.25, random_state = 10)

In [25]:
Invest_train.shape

(150000, 10)

In [26]:
Return_train.shape

(150000,)

In [27]:
Return_train[0:5]

array([3.08, 2.05, 4.97, 5.32, 0.75])

In [28]:
Return_train[0:5]


array([3.08, 2.05, 4.97, 5.32, 0.75])

In [29]:
Return_train

array([3.08, 2.05, 4.97, ..., 3.69, 4.91, 2.59])

In [30]:
#from sklearn.tree import DecisionTreeRegressor

#RegDec = DecisionTreeRegressor(min_samples_split = 5,random_state = 10, max_depth= 3)



In [31]:
#RegDec.fit(Invest_train, Return_train)

In [32]:
#Treepredict = RegDec.predict(Invest_test)

In [33]:
#RegDec.get_params()

In [34]:
#from sklearn.metrics import mean_squared_error

#MSE= mean_squared_error(Return_test, Treepredict)

In [35]:
# new plan  is to strip invest2 of variables to deduce root. 

In [36]:
#MSE

In [37]:
#MSE


In [38]:
from sklearn.tree import DecisionTreeRegressor, plot_tree


#RegDec = DecisionTreeRegressor(min_samples_split = 5,random_state = 10,ccp_alpha = 8000, max_leaf_nodes=3, min_impurity_decrease = 5, max_depth = 5)
RegDec = DecisionTreeRegressor(random_state = 0)

test  = Invest_train[0:500]

test1 = test

In [39]:
Return_train.shape

(150000,)

In [40]:
Invest_train.shape

(150000, 10)

In [41]:
RegDec.fit(Invest_train[0:100], Return_train[0:100])

DecisionTreeRegressor(random_state=0)

In [42]:
Treepredict = RegDec.predict(Invest_test)

In [43]:
Invest_test.shape

(50000, 10)

In [44]:
Treepredict[1001:2001]

array([ 3.01, -0.47,  2.05,  3.42,  3.57,  2.16,  1.26,  4.39,  3.01,
        4.72,  5.23,  3.07, 27.83,  1.87,  5.68,  4.29,  3.01,  4.72,
        1.26,  0.96,  1.03,  1.87,  4.48,  6.76,  1.03,  5.39, 27.83,
        0.7 ,  3.28,  3.57,  1.65,  0.42, -1.69,  4.79,  4.97,  1.65,
        5.22,  2.59,  3.42,  1.03,  2.09,  1.26,  0.96, -0.47,  0.96,
       -5.66, -0.47, 27.83,  4.88, 27.83,  1.26,  3.93,  0.7 ,  3.21,
        4.89,  5.32, -0.95,  6.29, -2.52, -0.83,  4.29,  3.99,  3.21,
        2.48,  1.03, 27.83,  3.93,  1.87,  3.55,  2.09,  0.96,  1.26,
        1.03,  5.14,  2.41, -2.52,  2.02,  3.01,  2.69,  2.65, -1.69,
        5.14,  3.55,  3.21,  5.59,  3.67,  2.49,  0.42,  2.49,  2.41,
        3.57,  1.03, -0.47,  5.32,  1.55,  2.41,  3.74,  1.87,  3.99,
        0.88,  5.68, -0.95,  0.42,  4.89,  2.09,  1.03, -1.69,  2.25,
        1.87,  4.97,  3.28,  1.9 ,  3.66,  0.88,  3.99,  3.21,  5.42,
        3.93,  3.21,  3.74, -0.47,  0.42,  0.88,  1.03,  2.49,  5.14,
        2.41,  3.74,

In [45]:
Treepredict.shape

(50000,)

In [46]:
Treepredict

array([3.55, 2.3 , 5.22, ..., 6.29, 3.55, 3.28])

In [47]:
Treepredict
#RegDec.get_params()

array([3.55, 2.3 , 5.22, ..., 6.29, 3.55, 3.28])

In [48]:
print(Treepredict)

[3.55 2.3  5.22 ... 6.29 3.55 3.28]


In [49]:
from sklearn.metrics import mean_squared_error

MSE= mean_squared_error(Return_test, Treepredict)

In [50]:
Invest_train[0].mean()

42.0709999923706

In [51]:
MSE

0.8857498839999998

In [52]:
RegDec.get_params()

{'ccp_alpha': 0.0,
 'criterion': 'squared_error',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': 0,
 'splitter': 'best'}

In [52]:
from sklearn import tree 


In [53]:
%matplotlib inline

In [54]:
plt.figure(figsize=(82,80))


<Figure size 8200x8000 with 0 Axes>

<Figure size 8200x8000 with 0 Axes>

In [1]:


tree.plot_tree(RegDec, feature_names = ["roa_ratio","horizon","amount", "price_Buy"," inflation ", " inflation", "ESG_ranking", "EPS "," net profit","current", "roa", "roe" ], filled = True, rounded= True)


NameError: name 'tree' is not defined

In [56]:
import matplotlib.style  as mplstyle


mplstyle.use("fast")


In [57]:
plt.show()

## 

In [58]:
 #from sklearn.tree import export_graphviz
#graphic = export_graphviz(RegDec, feature_names = ["horizon","amount", "price_Buy", "Volatility_Buy", "expected return"," inflation", "ESG_ranking", "EPS "," net profit","current", "roa", "roe" ], filled = True, rounded= True)


In [78]:
#import graphviz


#Visual = graphviz.Source(graphic)

#Visual.render("decision_tree_regressor")
#Visual.View()

ExecutableNotFound: failed to execute PosixPath('dot'), make sure the Graphviz executables are on your systems' PATH