In [1]:
!pip3 install --upgrade pip

In [23]:
import pandas as pd

In [24]:
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
import seaborn as sns

In [25]:
Invest  = pd.read_csv('final_transactions_dataset.csv')

In [26]:
Invest1 = Invest[0:200000]


In [27]:
Invest1.describe

<bound method NDFrame.describe of         Unnamed: 0 company  sector  horizon (days)  amount date_BUY_fix  \
0                0     BBY  RETAIL               2     100   2017-05-25   
1                1     BAC    BANK             330   15000   2016-11-22   
2                2     AXP    BANK               7    3000   2016-09-27   
3                3     KSS  RETAIL               5   20000   2016-10-11   
4                4     JPM    BANK             360   15000   2015-03-12   
...            ...     ...     ...             ...     ...          ...   
199995      246667      GM    AUTO             120     500   2015-06-09   
199996      246668      GM    AUTO             150    1500   2014-03-04   
199997      246669     JPM    BANK             270    1500   2016-09-19   
199998      246670     HMC    AUTO              90    2000   2015-01-16   
199999      246671      DB    BANK              80    4000   2016-12-27   

       date_SELL_fix  price_BUY  price_SELL  Volatility_Buy  ... 

In [28]:
Return = Invest1['nominal_return']

In [29]:
Invest2 = Invest1.drop(['roa_ratio','expected_return (yearly)','Unnamed: 0','company','sector','date_BUY_fix','date_SELL_fix','price_SELL','Volatility_sell','investment','Sharpe Ratio','PE_ratio','PS_ratio','PB_ratio'], axis = 1)

In [30]:
Invest2

horizon (days)  amount  price_BUY  Volatility_Buy  inflation  \
0                    2     100  55.551804        0.383666       1.96   
1                  330   15000  18.616749        0.322809      -0.20   
2                    7    3000  59.862297        0.238642      -0.20   
3                    5   20000  38.216724        0.428559      -0.20   
4                  360   15000  51.869335        0.194612      -0.50   
...                ...     ...        ...             ...        ...   
199995             120     500  28.741871        0.224747      -0.50   
199996             150    1500  28.542963        0.242287      -0.15   
199997             270    1500  58.351299        0.253744      -0.20   
199998              90    2000  30.840000        0.191505      -0.50   
199999              80    4000  17.665504        0.525184      -0.20   

        nominal_return  ESG_ranking  EPS_ratio  NetProfitMargin_ratio  \
0            -0.037225         12.0       3.73                   3.01   
1             0.324317         26.3       1.26                  15.70   
2            -0.005756         19.8       5.64                  15.68   
3            -0.058388         12.9       3.27                   3.17   
4             0.003444         27.9       5.46                  19.91   
...                ...          ...        ...                    ...   
199995       -0.051145         30.6       2.70                   2.98   
199996       -0.078845         30.6       1.83                   1.94   
199997        0.326308         27.9       5.80                  20.86   
199998        0.136835         28.5       3.08                   4.83   
199999        0.035928         30.0      -1.31                  -3.43   

        current_ratio  roe_ratio  
0                1.49      26.69  
1                0.92       5.54  
2                1.91      25.78  
3                1.60      11.35  
4                0.99       8.91  
...               ...        ...  
199995           1.22      11.97  
199996           1.25       7.46  
199997           1.04       8.66  
199998           1.23       9.24  
199999           0.75      -2.10  

[200000 rows x 11 columns]

In [31]:
Invest2.shape

(200000, 11)

In [32]:
Return_A = Invest2.iloc[:,6].values


In [33]:
Return_A.shape

(200000,)

In [34]:
Return.shape

(200000,)

In [35]:
Invest3 =Invest2.drop(['nominal_return'], axis = 1)


In [36]:
Invest2.shape

(200000, 11)

In [37]:
Invest3.shape

(200000, 10)

In [38]:
Invest3

horizon (days)  amount  price_BUY  Volatility_Buy  inflation  \
0                    2     100  55.551804        0.383666       1.96   
1                  330   15000  18.616749        0.322809      -0.20   
2                    7    3000  59.862297        0.238642      -0.20   
3                    5   20000  38.216724        0.428559      -0.20   
4                  360   15000  51.869335        0.194612      -0.50   
...                ...     ...        ...             ...        ...   
199995             120     500  28.741871        0.224747      -0.50   
199996             150    1500  28.542963        0.242287      -0.15   
199997             270    1500  58.351299        0.253744      -0.20   
199998              90    2000  30.840000        0.191505      -0.50   
199999              80    4000  17.665504        0.525184      -0.20   

        ESG_ranking  EPS_ratio  NetProfitMargin_ratio  current_ratio  \
0              12.0       3.73                   3.01           1.49   
1              26.3       1.26                  15.70           0.92   
2              19.8       5.64                  15.68           1.91   
3              12.9       3.27                   3.17           1.60   
4              27.9       5.46                  19.91           0.99   
...             ...        ...                    ...            ...   
199995         30.6       2.70                   2.98           1.22   
199996         30.6       1.83                   1.94           1.25   
199997         27.9       5.80                  20.86           1.04   
199998         28.5       3.08                   4.83           1.23   
199999         30.0      -1.31                  -3.43           0.75   

        roe_ratio  
0           26.69  
1            5.54  
2           25.78  
3           11.35  
4            8.91  
...           ...  
199995      11.97  
199996       7.46  
199997       8.66  
199998       9.24  
199999      -2.10  

[200000 rows x 10 columns]

In [39]:
Invest3.shape

(200000, 10)

In [40]:
Invest3

horizon (days)  amount  price_BUY  Volatility_Buy  inflation  \
0                    2     100  55.551804        0.383666       1.96   
1                  330   15000  18.616749        0.322809      -0.20   
2                    7    3000  59.862297        0.238642      -0.20   
3                    5   20000  38.216724        0.428559      -0.20   
4                  360   15000  51.869335        0.194612      -0.50   
...                ...     ...        ...             ...        ...   
199995             120     500  28.741871        0.224747      -0.50   
199996             150    1500  28.542963        0.242287      -0.15   
199997             270    1500  58.351299        0.253744      -0.20   
199998              90    2000  30.840000        0.191505      -0.50   
199999              80    4000  17.665504        0.525184      -0.20   

        ESG_ranking  EPS_ratio  NetProfitMargin_ratio  current_ratio  \
0              12.0       3.73                   3.01           1.49   
1              26.3       1.26                  15.70           0.92   
2              19.8       5.64                  15.68           1.91   
3              12.9       3.27                   3.17           1.60   
4              27.9       5.46                  19.91           0.99   
...             ...        ...                    ...            ...   
199995         30.6       2.70                   2.98           1.22   
199996         30.6       1.83                   1.94           1.25   
199997         27.9       5.80                  20.86           1.04   
199998         28.5       3.08                   4.83           1.23   
199999         30.0      -1.31                  -3.43           0.75   

        roe_ratio  
0           26.69  
1            5.54  
2           25.78  
3           11.35  
4            8.91  
...           ...  
199995      11.97  
199996       7.46  
199997       8.66  
199998       9.24  
199999      -2.10  

[200000 rows x 10 columns]

In [41]:
Invest4 = Invest3.drop(['NetProfitMargin_ratio'], axis = 1)

In [42]:
Invest4.shape

(200000, 9)

In [43]:
Invest3

horizon (days)  amount  price_BUY  Volatility_Buy  inflation  \
0                    2     100  55.551804        0.383666       1.96   
1                  330   15000  18.616749        0.322809      -0.20   
2                    7    3000  59.862297        0.238642      -0.20   
3                    5   20000  38.216724        0.428559      -0.20   
4                  360   15000  51.869335        0.194612      -0.50   
...                ...     ...        ...             ...        ...   
199995             120     500  28.741871        0.224747      -0.50   
199996             150    1500  28.542963        0.242287      -0.15   
199997             270    1500  58.351299        0.253744      -0.20   
199998              90    2000  30.840000        0.191505      -0.50   
199999              80    4000  17.665504        0.525184      -0.20   

        ESG_ranking  EPS_ratio  NetProfitMargin_ratio  current_ratio  \
0              12.0       3.73                   3.01           1.49   
1              26.3       1.26                  15.70           0.92   
2              19.8       5.64                  15.68           1.91   
3              12.9       3.27                   3.17           1.60   
4              27.9       5.46                  19.91           0.99   
...             ...        ...                    ...            ...   
199995         30.6       2.70                   2.98           1.22   
199996         30.6       1.83                   1.94           1.25   
199997         27.9       5.80                  20.86           1.04   
199998         28.5       3.08                   4.83           1.23   
199999         30.0      -1.31                  -3.43           0.75   

        roe_ratio  
0           26.69  
1            5.54  
2           25.78  
3           11.35  
4            8.91  
...           ...  
199995      11.97  
199996       7.46  
199997       8.66  
199998       9.24  
199999      -2.10  

[200000 rows x 10 columns]

In [44]:
Invest4

horizon (days)  amount  price_BUY  Volatility_Buy  inflation  \
0                    2     100  55.551804        0.383666       1.96   
1                  330   15000  18.616749        0.322809      -0.20   
2                    7    3000  59.862297        0.238642      -0.20   
3                    5   20000  38.216724        0.428559      -0.20   
4                  360   15000  51.869335        0.194612      -0.50   
...                ...     ...        ...             ...        ...   
199995             120     500  28.741871        0.224747      -0.50   
199996             150    1500  28.542963        0.242287      -0.15   
199997             270    1500  58.351299        0.253744      -0.20   
199998              90    2000  30.840000        0.191505      -0.50   
199999              80    4000  17.665504        0.525184      -0.20   

        ESG_ranking  EPS_ratio  current_ratio  roe_ratio  
0              12.0       3.73           1.49      26.69  
1              26.3       1.26           0.92       5.54  
2              19.8       5.64           1.91      25.78  
3              12.9       3.27           1.60      11.35  
4              27.9       5.46           0.99       8.91  
...             ...        ...            ...        ...  
199995         30.6       2.70           1.22      11.97  
199996         30.6       1.83           1.25       7.46  
199997         27.9       5.80           1.04       8.66  
199998         28.5       3.08           1.23       9.24  
199999         30.0      -1.31           0.75      -2.10  

[200000 rows x 9 columns]

In [45]:

Invest_A = Invest3.iloc[:,0:12].values


In [46]:
Invest_A[0:4]

array([[ 2.00000000e+00,  1.00000000e+02,  5.55518036e+01,
         3.83665561e-01,  1.96000000e+00,  1.20000000e+01,
         3.73000000e+00,  3.01000000e+00,  1.49000000e+00,
         2.66900000e+01],
       [ 3.30000000e+02,  1.50000000e+04,  1.86167488e+01,
         3.22809147e-01, -2.00000000e-01,  2.63000000e+01,
         1.26000000e+00,  1.57000000e+01,  9.20000000e-01,
         5.54000000e+00],
       [ 7.00000000e+00,  3.00000000e+03,  5.98622971e+01,
         2.38641964e-01, -2.00000000e-01,  1.98000000e+01,
         5.64000000e+00,  1.56800000e+01,  1.91000000e+00,
         2.57800000e+01],
       [ 5.00000000e+00,  2.00000000e+04,  3.82167244e+01,
         4.28559475e-01, -2.00000000e-01,  1.29000000e+01,
         3.27000000e+00,  3.17000000e+00,  1.60000000e+00,
         1.13500000e+01]])

In [47]:
Invest_A.shape

(200000, 10)

In [48]:
from sklearn.model_selection import train_test_split

Invest_train, Invest_test, Return_train, Return_test = train_test_split(Invest_A, Return_A, test_size = 0.25, random_state = 10)

In [49]:
Invest_train.shape

(150000, 10)

In [50]:
Return_train.shape

(150000,)

In [51]:
Return_train[0:5]

array([28.5, 29.7, 27.3, 27.4, 31.6])

In [52]:
Return_train[0:5]


array([28.5, 29.7, 27.3, 27.4, 31.6])

In [53]:
Return_train

array([28.5, 29.7, 27.3, ..., 25.1, 27.4, 31.6])

In [54]:
#from sklearn.tree import DecisionTreeRegressor

#RegDec = DecisionTreeRegressor(min_samples_split = 5,random_state = 10, max_depth= 3)



In [55]:
#RegDec.fit(Invest_train, Return_train)

In [56]:
#Treepredict = RegDec.predict(Invest_test)

In [57]:
#RegDec.get_params()

In [58]:
#from sklearn.metrics import mean_squared_error

#MSE= mean_squared_error(Return_test, Treepredict)

In [59]:
# new plan  is to strip invest2 of variables to deduce root. 

In [60]:
#MSE

In [61]:
#MSE


In [62]:
from sklearn.tree import DecisionTreeRegressor, plot_tree


#RegDec = DecisionTreeRegressor(min_samples_split = 5,random_state = 10,ccp_alpha = 8000, max_leaf_nodes=3, min_impurity_decrease = 5, max_depth = 5)
RegDec = DecisionTreeRegressor(random_state = 0)

test  = Invest_train[0:500]

test1 = test

In [63]:
Return_train.shape

(150000,)

In [64]:
Invest_train.shape

(150000, 10)

In [65]:
RegDec.fit(Invest_train[0:100], Return_train[0:100])

DecisionTreeRegressor(random_state=0)

In [66]:
Treepredict = RegDec.predict(Invest_test)

In [67]:
Invest_test.shape

(50000, 10)

In [68]:
Treepredict[1001:2001]

array([12. , 31.1, 30. , 12. , 16.3, 26.9, 26.9, 27.3, 16.3, 22.3, 12.9,
       14.8, 22.8, 26.9, 27.9, 14.8, 14.7, 22.3, 26.9, 25.1, 29.7, 24.8,
       27.9, 27.9, 25.1, 25.1, 22.8, 31.6, 12.9, 16.3, 16.5, 27.4, 31.1,
       14.8, 27.3, 16.5, 19.8, 31.6, 16.3, 12.9, 14.7, 26.9, 30. , 31.1,
       12.9, 30. , 31.1, 22.8, 27.3, 22.8, 31.6, 25.1, 26.3, 27.3, 17.6,
       27.4, 31.1, 31.6, 30. , 31.1, 14.8, 27.9, 16.3, 14.5, 12.9, 22.3,
       16.3, 26.9, 17.6, 14.7, 26.3, 26.3, 29.7, 19.8, 24.8, 30. , 16.5,
       12.9, 24.8, 26.3, 31.1, 19.8, 12. , 12.9, 14.8, 25.1, 14.5, 24.8,
       12. , 29.7, 16.3, 26.3, 31.1, 27.9, 26.9, 14.5, 25.1, 16.5, 14.8,
       12.9, 19.8, 31.1, 26.3, 17.6, 16.5, 25.1, 31.1, 16.5, 31.6, 19.8,
       25.1, 29.7, 25.1, 31.6, 14.8, 16.3, 22.3, 16.3, 12. , 25.1, 31.1,
       20.5, 30. , 12.9, 12.9, 19.8, 14.8, 25.1, 27.3, 16.3, 19.8, 31.6,
       12.9, 16.5, 16.5, 14.5, 26.9, 31.1, 29.7, 22.8, 17.6, 30.6, 27.4,
       31.6, 28.5, 30.6, 14.5, 31.6, 29.7, 12. , 26

In [69]:
Treepredict.shape

(50000,)

In [70]:
Treepredict

array([12. , 16.5, 22.3, ..., 22.3, 12. , 17.6])

In [71]:
Treepredict
#RegDec.get_params()

array([12. , 16.5, 22.3, ..., 22.3, 12. , 17.6])

In [72]:
print(Treepredict)

[12.  16.5 22.3 ... 22.3 12.  17.6]


In [73]:
from sklearn.metrics import mean_squared_error

MSE= mean_squared_error(Return_test, Treepredict)

In [74]:
Invest_train[0].mean()

41.72494692137133

In [75]:
MSE

0.0301101999999998

## 